### PR TITLE
re-add pagination

### PR DESCRIPTION
**Pull request by parkervcp**
This resolves many issues I found on top of the pagination issue.

@CamiloHernandez This also re-resolves the #5 issue in a more permanent way.

### CODE REVIEW

**Comment by parkervcp** [comment]
If you can test this out that'd be great

**Comment by parkervcp** [comment]
Or I am still working on this.

**Comment by ccuetoh** [comment]
As far as I can tell everything works ok. Good work!

Though I must say that I can't fully test the pagination since it looks like only Client calls come with it, and they are not yet implemented.

**Comment by parkervcp** [comment]
Every single application api endpoint has pagination.

**Pull request merged**
